outdir: /mnt/nfs2_external/rscc/home/liuxin/3.second_batch_WGBS
ref: /mnt/nfs1_external/rsaa/home/liuxin/data_pasteur/12_epigenome/CHM13_ref
sample: /mnt/nfs2_external/rscc/home/liuxin/3.second_batch_WGBS/sample_2.txt
threads:
  bis_align: 18
  bis_call: 18
  bis_dedul: 18
  soapnuke: 18
